### ISSUE TITLE
Unwinding support

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#10]
Implement unwinding support for `x86_64-fortanix-unknown-sgx`.

**Comment by jethrogb** [comment]
Also backtrace support. I'm not sure if that's related to unwinding or not.

**Comment by VardhanThigle** [comment]
@jethrogb We are supporting Unwind and Backtrace. Have we planned more changes under scope of this issue?

**Comment by VardhanThigle** [comment]
Closing the issue since we have unwind and back trace support.
