### ISSUE TITLE
Attestation example not working with Report type

### ISSUE THREAD

**Issue by lkatalin** [fortanix/rust-sgx#124]
I am following the Attestation examples from your [Docs](https://edp.fortanix.com/docs/examples/attestation/). However, I get a compilation error with `cargo build`, indicating that `sgx_isa::Report` does not have any `for_self()` or `for_target()` methods:

```
error[E0599]: no function or associated item named `for_self` found for type `sgx_isa::Report` in the current scope
 --> src/main.rs:4:47
  |
4 |     let targetinfo = Targetinfo::from(Report::for_self());
  |                                               ^^^^^^^^ function or associated item not found in `sgx_isa::Report`

error: aborting due to previous error
```

Looking at the [Report](https://edp.fortanix.com/docs/api/sgx_isa/struct.Report.html#method.for_self), these do seem to be missing.

Could you advise?

**Comment by jethrogb** [comment]
Have you configured the `sgxstd` feature on the `sgx-isa` crate in your dependencies?

**Comment by lkatalin** [comment]
I believe so. I have this line in my Cargo.toml as shown on that page:
```
[dependencies]
sgx-isa = { version = "0.2", features = ["sgxstd"] }
```
I've also tried `version = "^0.2"`.

This is `main.rs`:
```
use sgx_isa::{Report, Targetinfo};

fn main() {
    let targetinfo = Targetinfo::from(Report::for_self());
}
```

I'm new to Rust and am not sure whether this is a bug or my error, so apologies in case of the latter. I would ask in the #rust-sgx Slack channel, but it appears to be down.

**Comment by jethrogb** [comment]
@lkatalin Why do you think the Slack channel is down? As far as I can tell it's working fine. How are you trying to access it?

**Comment by jethrogb** [comment]
Are you compiling for SGX? The attestation functions only exist when you're compiling for SGX with `--target x86_64-fortanix-unknown-sgx`.

**Comment by lkatalin** [comment]
I went back through the steps and it looks like I did stop compiling for the target while debugging. It now compiles properly - thank you. I had started trying to debug because I get an enclave panic when I run the example. Looks like I'm either not setting some permissions correctly or a dummy signature is not working, but not sure:

```
$ cargo run --target x86_64-fortanix-unknown-sgx
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `ftxsgx-runner-cargo target/x86_64-fortanix-unknown-sgx/debug/report-enclave`
Error: Os { code: 1, kind: PermissionDenied, message: "permission denied" }
Error while executing SGX enclave.
Enclave panicked: Exited with status code 1
ERROR: while running "ftxsgx-runner" "target/x86_64-fortanix-unknown-sgx/debug/report-enclave.sgxs" "--signature" "dummy" got exit code: 255
```

I'm following the Attestation example fairly literally and it's the first thing I am building with this code; maybe I am missing some steps? I'm also trying to look through the source code for [examples](https://github.com/fortanix/rust-sgx/tree/master/examples).

Re: Slack, it appears to be back up. So, if it's more appropriate, I can ask questions there instead.

**Comment by jethrogb** [comment]
> Error: Os { code: 1, kind: PermissionDenied, message: "permission denied" }

Hmm I've not seen this error before. What is the output of `ls -la /dev/*sgx`?

Yes, Slack is a better venue for support questions.
