### ISSUE TITLE
Allow passing args to Command

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#136]
The ABI will let you pass arguments to `main_entry`, but neither `enclave_runner::Command` nor `ftxsgx-runner` will let you do this at the moment.

When this feature is added, it should be clearly documented that this is not an appropriate channel for passing secrets or security configuration.

**Comment by kaimast** [comment]
[This site](https://edp.fortanix.com/docs/concepts/rust-std/) says _"Configuration data that isn't relevant to security may be provided as a command-line argument, read from stdin, or appended as unmeasured data."_ 
But there is indeed no way to pass arguments to the enclave right now. 

I was hoping to run multiple enclaves on the same machine and pass which port they are listening on as a command line argument, but this seems impossible right now?

**Comment by kaimast** [comment]
Any ideas how to work around this? 

If not, would patches for the `ftxsgx-runner` to add this feature be welcome?

**Comment by jethrogb** [comment]
PRs never expected, always appreciated :)
