### ISSUE TITLE
GDB: Instruction for adding setting to Cargo.toml should be on top

### ISSUE THREAD

**Issue by parthsane** [fortanix/rust-sgx#149]
In
https://edp.fortanix.com/docs/tasks/debugging/

I feel that the point number 9
```
In Cargo.toml you can configure panics to abort rather than unwind as follows, to preserve the call stack for the debugger
```
should be on top. Maybe as an optional point.

**Comment by jethrogb** [comment]
Agreed that should be separate from the debugging steps. Also, the paragraph that starts with "Currently, GDB" should really be its own section, not part of the TCS section. Please file a PR against the EDP website repo (on BitBucket) with your changes.
