### ISSUE TITLE
Build break running "tls" example

### ISSUE THREAD

**Issue by thanksunix** [fortanix/rust-sgx#151]
Hi Dears,

After setup the EDP envvironment,
I was able to run hello_world and "mpsc-crypto-mining" demo .

But the tls sample failed to compile with below error message, 
Could you someone provides help with this?

------
root@localhost:/opt/aecs/tls# cargo run --target x86_64-fortanix-unknown-sgx
   Compiling mbedtls-sys-auto v2.16.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.0.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.1.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.10.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.11.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.12.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.13.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.14.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.15.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.2.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.3.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.4.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.5.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.6.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.7.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.8.rcgu.o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.build_script_build.dqcixmu2-cgu.9.rcgu.o" "-o" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917" "/opt/aecs/tls/target/debug/build/mbedtls-sys-auto-0775060092cdb917/build_script_build-0775060092cdb917.3ykza5nonklooy3m.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/opt/aecs/tls/target/debug/deps" "-L" "/usr/local/occlum/lib" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/opt/aecs/tls/target/debug/deps/libcmake-dd35b70e5434cca4.rlib" "/opt/aecs/tls/target/debug/deps/libcc-b8a99785cef6f82c.rlib" "/opt/aecs/tls/target/debug/deps/libbindgen-3e93b51edd016aba.rlib" "/opt/aecs/tls/target/debug/deps/libcexpr-7728d6a3719c34cb.rlib" "/opt/aecs/tls/target/debug/deps/libnom-10e95fdff589b222.rlib" "/opt/aecs/tls/target/debug/deps/libmemchr-3392305ea1692622.rlib" "/opt/aecs/tls/target/debug/deps/libsyntex_syntax-c4057b25affb05bf.rlib" "/opt/aecs/tls/target/debug/deps/libsyntex_errors-b6a8d6425ec2ea40.rlib" "/opt/aecs/tls/target/debug/deps/libsyntex_pos-7f3e4f536aa3033f.rlib" "/opt/aecs/tls/target/debug/deps/libunicode_xid-371fa10b963800d7.rlib" "/opt/aecs/tls/target/debug/deps/librustc_serialize-6eb039b2afad64e6.rlib" "/opt/aecs/tls/target/debug/deps/libbitflags-7a33f98c7bd88582.rlib" "/opt/aecs/tls/target/debug/deps/liblog-9ad5a9600654a591.rlib" "/opt/aecs/tls/target/debug/deps/liblog-80842988ffb0f524.rlib" "/opt/aecs/tls/target/debug/deps/libcfg_if-a08de7a5a9159475.rlib" "/opt/aecs/tls/target/debug/deps/libterm-00e99443d990b40d.rlib" "/opt/aecs/tls/target/debug/deps/libclang_sys-cb9d3b834455fdac.rlib" "/opt/aecs/tls/target/debug/deps/liblibc-443bf0c0b4044861.rlib" "/opt/aecs/tls/target/debug/deps/libglob-87d12ac27d651ae7.rlib" "/opt/aecs/tls/target/debug/deps/libbitflags-9e47e08e56009082.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-de75be4c83b6efd4.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-5e1151a25df11f73.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-2212beffaf95e9d4.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-9edf6f22c587f2ff.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-db22c18283ab0d6a.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-e3213ffafe6f6a33.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-1ebeea1a6da75a37.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-884052f472c414dd.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-083c64bb378ac8cd.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-456ec6faf8fefccb.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e26a05774e58a4db.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-aabf50e8b1504ba9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-768d8cc1a183e6c3.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c66fadb1060ceab3.rlib" "-Wl,-Bdynamic" "-lclang" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-de75be4c83b6efd4.rlib(std-de75be4c83b6efd4.std.dif66sg3-cgu.0.rcgu.o): undefined reference to symbol '__res_init@@GLIBC_2.2.5'
          //lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: Could not compile `mbedtls-sys-auto`.

**Comment by ssavvides** [comment]
https://github.com/fortanix/rust-mbedtls/issues/5
