### ISSUE TITLE
It is possible to pass parameters to the enclave from enclave_runner

### ISSUE THREAD

**Issue by YangZhou1997** [fortanix/rust-sgx#158]
Hi, 

I am seeking for a method that can pass shared memory (Shm) address to the enclave when the enclave_runner process calls enclave.run() and "traps" into Enclave. In this way, the enclave can access the shared memory created by the process before trapping into Enclave. 

Any comments and suggestions are highly appreciated! 

Best,
Yang

**Comment by jethrogb** [comment]
I've answered your question on Slack, closing since this is not a code issue.
