### ISSUE TITLE
Update libunwind

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#174]
Currently, we are using libunwind from LLVM 5. We should update to the latest version. Here's a summary of our changes https://github.com/llvm/llvm-project/compare/release/5.x...fortanix:release/5.x

We should also avoid the separate build & link step, but just build it as part of the rust compilation process. See also https://github.com/rust-lang/rust/pull/63173

**Comment by jethrogb** [comment]
I thought @VardhanThigle had made some progress here but I can't find the branch.

**Comment by AdrianCX** [comment]
First PR in rust-sgx: https://github.com/fortanix/rust-sgx/pull/228
Version update: https://github.com/fortanix/rust-sgx/pull/234

Pending: rust-lang changes

**Comment by jethrogb** [comment]
@AdrianCX is this fixed?

**Comment by AdrianCX** [comment]
Yes.

For book keeping, these are the PRs:

1. rust-sgx: https://github.com/fortanix/rust-sgx/pull/228
2. Version update: https://github.com/fortanix/rust-sgx/pull/234/files
3. rust-lang LLVM: https://github.com/rust-lang/llvm-project/pull/57/files
4. rust-lang build process changes: https://github.com/rust-lang/rust/pull/72937
