### ISSUE TITLE
Change AttributesFlags in sgx-isa Attributes

### ISSUE THREAD

**Issue by choco** [fortanix/rust-sgx#189]
Hello, I use `sgx-isa` in a wasm crate and I'd like to expose the attributes flags.
Currently I cast it down manually (since js has troubles with 64bit integers) but I was wondering if it would be possible to change `AttributesFlags` struct to a smaller integer type, since as far as I understand you only use the 8 bits at the moment.
Thanks for the great library!

**Comment by jethrogb** [comment]
The ISA specifies this is a 64-bit field, so I don't think any other size is appropriate.
