### ISSUE TITLE
sgx-detect: DCAP driver

### ISSUE THREAD

**Issue by w-woloszyn** [fortanix/rust-sgx#247]
Hello,

I am using DCAP driver and when I run `sgx-detect`, it reports that the SGX device could not be opened:
```

The SGX device (/dev/sgx or /dev/isgx) could not be opened: Is a directory (os error 21).

debug: Error opening device: Is a directory (os error 21)
debug: cause: Is a directory (os error 21)
```

I would like to point out that `/dev/sgx` is indeed a directory with `enclave` and `provision` files inside.

**Comment by jethrogb** [comment]
Hi @w-woloszyn which driver are you using specifically? From your description, it sounds like you're using the upstream driver, support for which [is pending](https://github.com/fortanix/rust-sgx/pull/181).

**Comment by w-woloszyn** [comment]
Thank you for your prompt response @jethrogb - I am using version 1.33, which is the latest one. Could you please advise me what version should I use?

**Comment by jethrogb** [comment]
Hmm I wasn't aware that Intel ported the latest versions of the patches to the module driver. Anything before 1.32 should work.

**Comment by w-woloszyn** [comment]
I see. I shall use 1.21 then. Thank you for your support, it saved me a lot of time!
