### ISSUE TITLE
 ERROR: while running "ftxsgx-runner" got signal: 7 

### ISSUE THREAD

**Issue by SipengXie** [fortanix/rust-sgx#249]
Hello, I'm trying to run a a project with command  `cargo run --target x86_64-fortanix-unknown-sgx `and the error occurs:

`ERROR: while running "ftxsgx-runner" "target/x86_64-fortanix-unknown-sgx/debug/test_gg18.sgxs" got signal: 7`

And then I run `cargo test  --target x86_64-fortanix-unknown-sgx` then I get this:

`test curv::elliptic::curves::secp256_k1::tests::test_invert ... ERROR: while running "ftxsgx-runner" "/home/victorxie/emerald-city-master/target/x86_64-fortanix-unknown-sgx/debug/deps/emerald_city-4893204ba51563b7.sgxs" got signal: 7`

Could you please give me some suggestions?

**Comment by jethrogb** [comment]
SIGBUS usually means you're running out of stack space. Try increasing the stack size, see https://edp.fortanix.com/docs/tasks/testing/.
