### ISSUE TITLE
Two more questions

### ISSUE THREAD

**Issue by SipengXie** [fortanix/rust-sgx#253]
Sorry to bother you again.
I‘m just new in rust and working on a project need SGX technique, and I have two more questions to ask.
(1)  I've written a rust lib and I hope only the lib can be run in the enclave, because other parts of my project (like GUI) do not need that. Can we do that ?
(2)  I've read that the std::fs is not supported by the fortanix, are there any other creates can be used?
Please give me some suggestions, thank you.

**Comment by jethrogb** [comment]
1. Yes. Write your enclave as a microservice that your GUI app calls out to.

2. You'll need to write a microservice for untrusted out-of-enclave storage.
