### ISSUE TITLE
Does Fortanix EDP support the gmp lib?

### ISSUE THREAD

**Issue by SipengXie** [fortanix/rust-sgx#265]
I'm trying to run a test of my project which uses rust-gmp, and everything works fine when I just use the command  `cargo test`.
When I use `cargo test --target x86_64-fortanix-unknown-sgx`, then the error occurs and says "cannot find gmp.lib".
So can we run our project using Fortanix EDP with gmp lib?

**Comment by jethrogb** [comment]
The best way to get community support is on Slack. I saw someone talking about GMP just last week. https://fortanix.com/runtime-encryption-slack
