### ISSUE TITLE
Port time

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#29]
https://crates.io/crates/time

Fortanix has an internal port that could be rebased

**Comment by akash-fortanix** [comment]
https://github.com/rust-lang-deprecated/time/pull/171

**Comment by akash-fortanix** [comment]
the PR got merged but awaiting release on crates.io

**Comment by akash-fortanix** [comment]
available on crates.io in time 0.1.41

**Comment by jethrogb** [comment]
https://github.com/rust-lang-deprecated/time/pull/172
