### ISSUE TITLE
Missing implementation for crate "aligned_alloc v0.1.3"

### ISSUE THREAD

**Issue by laocaoshilaocao** [fortanix/rust-sgx#324]
Hi, i am trying to use the dependence of `aligned_alloc-0.1.3` with fortanix EDP. However when i run `cargo run --target x86_64-fortanix-unknown-sgx` after adding `aligned_alloc = "0.1"` in the rust code. Error occurs:

```
 error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/aligned_alloc-0.1.3/src/lib.rs:20:5
   |
20 |     imp::aligned_alloc(size, align)
   |     ^^^ use of undeclared crate or module `imp`

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/aligned_alloc-0.1.3/src/lib.rs:28:5
   |
28 |     imp::aligned_free(ptr)
   |     ^^^ use of undeclared crate or module `imp`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `aligned_alloc`   
```
I also have checked the method provided on fortanix website which is conditional compilation in general. But i still have no clear idea of where should i add the `#[cfg(all(target_env = "sgx", target_vendor = "fortanix"))]`. The src file of the aligned_alloc is in the link `https://github.com/jonas-schievink/aligned_alloc.rs/tree/master/src`
Do u have any idea or suggestion of how can i solve that?

**Comment by laocaoshilaocao** [comment]
I have done several changes to src file:
In `cargo.toml` i added 
```
[target.'cfg(all(target_env = "sgx", target_vendor = "fortanix"))'.dependencies]
libc = "0.2"
winapi = "0.2"
kernel32-sys = "0.2"
```

In lib.src i added all `pub` functions and `mod imp` for unix before with a 
`#[cfg(all(target_env = "sgx", target_vendor = "fortanix"))]`

However, after trying to compile that crate i got
```
 --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/aligned_alloc-0.1.3/src/lib.rs:38:39
   |
38 |     use libc::{c_void, c_int, size_t, EINVAL, ENOMEM, free};
   |                                       ^^^^^^  ^^^^^^  ^^^^ no `free` in the root
   |                                       |       |
   |                                       |       no `ENOMEM` in the root
   |                                       no `EINVAL` in the root

error: aborting due to previous error
```
Is there anything i did wrong for the changes of that crate source file?

**Comment by jethrogb** [comment]
The crate you're trying to use is using system APIs that don't exist in SGX. You'll need to make changes to that crate's source code to support the SGX target. See https://edp.fortanix.com/docs/tasks/dependencies/.

Why are you trying to use this crate? Rust's allocator supports aligned allocations https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html

Closing this issue since it's with a 3rd party crate.

**Comment by laocaoshilaocao** [comment]
Because i want to implement `tensorflow in rust` in SGX. And it seems that the `aligned-alloc` crate is one of the necessary dependencies of tensorflow.

**Comment by jethrogb** [comment]
TensorFlow is written in C, since there is no libc for the x86_64-fortanix-unknown-sgx target it will be difficult to get that to work.

**Comment by laocaoshilaocao** [comment]
That is a bad news for me...
So do you have any commendation for the possible deep learning API that is supported by x86_64-fortanix-unknown-sgx target?

**Comment by jethrogb** [comment]
Not sure what part of the stack you need but https://github.com/apache/tvm supports EDP in parts.
