### ISSUE TITLE
Compilation fails due to no item named 'MAP_ANONYMOUS' - sgxs-loaders 

### ISSUE THREAD

**Issue by PatStiles** [fortanix/rust-sgx#377]
error[E0599]: no associated item named `MAP_ANONYMOUS` found for struct `MapFlags` in the current scope
   --> /Users/Patron/.cargo/registry/src/github.com-1ecc6299db9ec823/sgxs-loaders-0.3.2/src/isgx/mod.rs:163:48
    |
163 |                         Map::MAP_SHARED | Map::MAP_ANONYMOUS | Map::MAP_NORESERVE,
    |                                                ^^^^^^^^^^^^^ associated item not found in `MapFlags`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sgxs-loaders` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by PatStiles** [comment]
I tried using nightly-2021-12-15 but ran into the same error, any ideas? Should I try an even earlier version?

**Comment by jethrogb** [comment]
What OS are you using?

**Comment by PatStiles** [comment]
OSX Big Sur

**Comment by jethrogb** [comment]
Macs and OS X don't support SGX.
