### ISSUE TITLE
`Tcs` should not be a `NonNull` pointer

### ISSUE THREAD

**Issue by joboet** [fortanix/rust-sgx#407]
TCSs may be located at logical address zero. Defining [`Tcs`](https://github.com/fortanix/rust-sgx/blob/4bbac9583f3635026b35e8c17001b20973296301/intel-sgx/fortanix-sgx-abi/src/lib.rs#L446) to be [`NonNull`](https://doc.rust-lang.org/nightly/std/ptr/struct.NonNull.html) leads to bugs and even soundness issues that may be exposed to attackers. For instance, the internal [`abi::thread::current()`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/sgx/abi/thread.rs) function in the Rust standard library [does not check for zero pointers](https://github.com/rust-lang/rust/blob/a2cdcb3fea2baae5d20eabaa412e0d2f5b98c318/library/std/src/sys/sgx/abi/entry.S#L167) and unconditionally returns a `NonNull`. If the TCS address is null, this leads to immediate undefined behaviour.

**Comment by jethrogb** [comment]
Not sure I agree? It's always possible to place things at address zero, but we generally adhere to the convention to not do that so that we can use null as a niche or sentinel value.

**Comment by joboet** [comment]
Ok. Then this is simply a bug in `std` (it should really check for null pointers here). Thanks!

**Comment by jethrogb** [comment]
Not sure if it's necessary to do the check in std either, we can just define that TCSes are never placed at address 0?

**Comment by joboet** [comment]
No, since `EENTER` does not check if the address is null, only that it is well-aligned. Unconditionally casting the address to a `NonNull` (which is what `std` currently does) allows attackers to cause undefined behaviour within the enclave.

**Comment by jethrogb** [comment]
See discussion at https://github.com/rust-lang/rust/pull/98391#discussion_r962715979
