### ISSUE TITLE
`sgxs-tools` failed to compile  when using feature `pe2sgxs` on `nightly`

### ISSUE THREAD

**Issue by Taowyoo** [fortanix/rust-sgx#433]
This is because dependency  is failed to compile because of recent update of `rust nightly`:

[make unaligned_reference a hard error #102513](https://github.com/rust-lang/rust/pull/102513)

The dependency [jethrogb](https://github.com/jethrogb)/[pe-rs](https://github.com/jethrogb/pe-rs) need to update to fix this.

Created corresponding issue in [pe-rs](https://github.com/jethrogb/pe-rs) : https://github.com/jethrogb/pe-rs/issues/6

**Comment by Taowyoo** [comment]
Found this error from recent PR: https://github.com/fortanix/rust-sgx/pull/432

**Comment by jethrogb** [comment]
Can we please fix this ASAP as we are no longer able to test on stable

**Comment by Taowyoo** [comment]
Pls check https://github.com/jethrogb/pe-rs/pull/7
