### ISSUE TITLE
Test linker compatibility

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#47]
In the past, binutils 2.26.1 has been recommended. Testing is needed to see if this restriction still applies. If it does apply, consider switching to `rust-lld`.

**Comment by parthsane** [comment]
Tested the following versions to build and **successfully** ran a helloworld program using rust-sgx as 
instructed in https://github.com/fortanix/rust-sgx/issues/49

```
binutils-2.23.1
binutils-2.24
binutils-2.25
binutils-2.26
binutils-2.26.1
binutils-2.27
binutils-2.29.1
binutils-2.30
binutils-2.31.1```
