### ISSUE TITLE
dcap-retrieve-pckid reports error while running

### ISSUE THREAD

**Issue by yingjun-wu** [fortanix/rust-sgx#492]
You can locate the error code as follows:
https://github.com/fortanix/rust-sgx/blob/cdaabde0c1e6ee1a442b79ae524f08a6a49197fd/intel-sgx/dcap-retrieve-pckid/src/lib.rs#L92-L95

and the error is:
```
ERROR retrieving PCK ID: Error parsing requested signature type
```

This code actually generates a pck_cert_chain-based attesation. How can I configure it to generate a ppid_encrypted_rsa3072-based attesation?

**Comment by raoulstrackx** [comment]
Have you already installed a DCAP provider (i.e.,  the aesmd service is able to find a `libdcap_quoteprov.so` library)?

**Comment by yingjun-wu** [comment]
> Have you already installed a DCAP provider (i.e., the aesmd service is able to find a `libdcap_quoteprov.so` library)?

Yes,  The DCAP provider installation path is as follows:
```
root@43bbdd707f49:~/rust-sgx# whereis libdcap_quoteprov
libdcap_quoteprov: /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so
```

By the way, the running of PCKRetrievalTool provided by  [SGXDataCenterAttestationPrimitives](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master) is normal.

**Comment by raoulstrackx** [comment]
> Yes, The DCAP provider installation path is as follows:

That's probably the culprit. You need to remove it

**Comment by yingjun-wu** [comment]
> 
> That's probably the culprit. You need to remove it

After removing libdcap_quoteprov, the program still reports an error.

**Comment by raoulstrackx** [comment]
@yingjun-wu have you found the issue? For what it's worth, I've just re-executed this code and it's working as expected.

**Comment by yingjun-wu** [comment]
No，not yet. And I execute it and it returns the pck_cert_chain-based attesation in my environment. I'm not sure where is the problem?

**Comment by raoulstrackx** [comment]
I'm sure you thought of restarting the `aesmd` service after removing the DCAP provider, right?

You could also try the opposite: write your own dcap provider and ensure it always returns `Quote3Error::PlatformLibUnavailable`. At least you'll be able to see calls coming in to that library.

**Comment by yingjun-wu** [comment]
> I'm sure you thought of restarting the `aesmd` service after removing the DCAP provider, right?
> 
> You could also try the opposite: write your own dcap provider and ensure it always returns `Quote3Error::PlatformLibUnavailable`. At least you'll be able to see calls coming in to that library.

Okay, it's working as expected., mainly because aesm was not restarted after removing libdcap_quoteprov. By the way, if I still need a pck_cert_chain-based attesation later, can I still generate it?

**Comment by raoulstrackx** [comment]
Great!
Yes you can, but obviously you need to install a DCAP provider.

**Comment by raoulstrackx** [comment]
Closing the issue now
