### ISSUE TITLE
Is EDP the only way to develop SGX applications in rust?

### ISSUE THREAD

**Issue by digitalinformation** [fortanix/rust-sgx#510]
Is EDP the only way to develop SGX applications in rust?

**Comment by raoulstrackx** [comment]
No there are a few others. Enarx comes to mind, but that compiles down to webassembly and then runs that in an enclave. I can't recall numbers, but that must come with a performance penalty. I also think the project has been discontinued. (At least their last commit is from May and their CI is currently broken).
There's also a rust-sgx project from Baidu. I have no idea what the status of that is. Last time I looked (years ago) it was a thin wrapper around Intel's C/C++ SGX SDK. That meant you'd also have to write the interface between the enclave and the untrusted part of the application manually, which is very error prone and a perfect starting point for attackers.
EDP takes a different approach by providing programmers with an interface they are familiar with: the Rust standard library. TCP connections just works out of the box. So for many applications there isn't any need to run anything custom outside of the enclave. So you don't need to write any custom interface. Should there be a need though, there is a mechanism to provide you a `ByteBuffer` in the enclave. The most dangerous things like verifying pointers passed to the enclave, is still done for you.
Based on the question, I suspect that you are researching what SDK to use. So you may be interested in a few things you can read:
 - [Formal verification of EDP enclave entry and exit code](https://www.fortanix.com/blog/formal-verification-of-edp-enclave-entry-and-exit-code)
 - [Verifying correctness of Intel SGX software mitigations in Fortanix EDP](https://www.fortanix.com/blog/verifying-correctness-of-intel-sgx-software-mitigations-in-fortanix-edp)
 - [Secure compilation to modern processors](https://ieeexplore.ieee.org/abstract/document/6266159/)

Enjoy!
