### ISSUE TITLE
 when executing start_pyspark_pi_on_local_sgx.sh, the following error was reported

### ISSUE THREAD

**Issue by zhengjujing** [fortanix/rust-sgx#527]
There was no problem executing start_spark_pi_on_local_sgx.sh, and there was no problem running start_python_numpy_on_sgx.sh. However, when executing start_pyspark_pi_on_local_sgx.sh, the following error was reported (bigdl=2.20, pyspark=31.3, spark=31.3)

bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/ppml/trusted-big-data-ml/work/spark-3.1.2/jars/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/ppml/trusted-big-data-ml/work/spark-3.1.2/jars/slf4j-reload4j-1.7.35.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Spark config:
(spark.python.use.daemon,false)
(spark.app.name,wordcount.py)
(spark.submit.pyFiles,)
(spark.python.worker.reuse,false)
(spark.submit.deployMode,client)
(spark.master,local[4])
####### @ SparkSubmit: sgxLogLevel None
error: Unexpected memory fault occurred inside PAL (0x7e934c7f0)
error: Enclave EADD returned -12
error: Adding pages (free) to enclave failed: -12
error: load_enclave() failed with error -12

**Comment by jethrogb** [comment]
Your report doesn't appear to be related to this project.
