### ISSUE TITLE
Publish new version of sgxs to crates.io

### ISSUE THREAD

**Issue by jimmyyip-crypto** [fortanix/rust-sgx#558]
**Description**
Publish a new version of `sgxs` to crates.io.

**Problem or Motivation:**
Some dependencies in the latest released version `v0.7.4` are outdated. And some of them may even have known vulnerability.
e.g. https://rustsec.org/advisories/RUSTSEC-2020-0071.
The dependencies have been updated on master branch. It will be great if you can create new tag from there.

**Proposed solution:**
Follow the steps in https://github.com/fortanix/rust-sgx?tab=readme-ov-file#about-creating-release-and-publishing-to-cratesio to publish a new version of `sgxs`

**Benefits:**
Update dependencies which are with vulnerability and make the crate publicly available.

**Describe alternatives you've considered:**
Users of `sgxs` may also fork this repository and update the reference in Cargo.toml as a git repository. But making it available on `crates.io` is more convenient to the users.

**Comment by Taowyoo** [comment]
New version of `sgxs` `0.8.0` is published, please check https://crates.io/crates/sgxs.
