### ISSUE TITLE
dcap-ql: Update mbedtls?

### ISSUE THREAD

**Issue by DragonDev1906** [fortanix/rust-sgx#567]
Is there a reason why mbedtls is (still) restricted to `<0.10.0` (6 Months old)? The currently version is 0.12.3.

```toml
mbedtls = { version = ">=0.8.0, <0.10.0", default-features = false, features = ["std"], optional = true }
```

**Comment by Taowyoo** [comment]
New version `0.4.0` published, please check https://crates.io/crates/dcap-ql
