### ISSUE TITLE
`ioctl` has been yanked.

### ISSUE THREAD

**Issue by Pratyush** [fortanix/rust-sgx#9]
The sgxs crate depends on the `ioctl` crate, but this crate has been yanked, and so one cannot execute `cargo install libenclave tools && cargo install sgxs-tools`.

**Comment by Pratyush** [comment]
I tried to replace `ioctl` with `nix`, but attempting to run a compiled enclave results in a `NOTTY` error inside `EnclaveLoad`.

**Comment by jethrogb** [comment]
ENOTTY normally indicates that the ioctl you're trying to call does not match one that's defined in the kernel. Are you sure you are using the right definitions and kernel driver?

We have internally ported to nix without issue.

**Comment by Pratyush** [comment]
Hmm yeah I realized that. I switched to `nix` on the `isgxv3` branch of my fork, and now my enclave runs fine. I'll open a pull request updating the main branch and the `isgxv3` branch to `nix`.

**Comment by jethrogb** [comment]
`nix` is now used instead
